version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: express_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: expressdb
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: express_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/expressdb
      - PORT=3000
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo_data: